USE MASTER
GO

IF DB_ID('QLBanHang') IS NOT NULL 
	DROP DATABASE QLBanHang
GO

CREATE DATABASE QLBanHang
GO

USE QLBanHang
GO

CREATE TABLE USER_TABLE
(
	ID INT IDENTITY(1, 1) NOT NULL,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	FULLNAME NVARCHAR(255),
	BOB DATETIME,
	ROLE INT,

	CONSTRAINT PK_USER
	PRIMARY KEY (ID)
)
GO

CREATE TABLE STAFF
(
	ID INT IDENTITY(1, 1) NOT NULL,
	ID_USER INT,
	ID_BRANCH INT,

	CONSTRAINT PK_STAFF
	PRIMARY KEY (ID)
)
GO

CREATE TABLE CUSTOMER
(
	ID INT IDENTITY(1, 1) NOT NULL,
	ID_USER INT,

	CONSTRAINT PK_CUSTOMER
	PRIMARY KEY (ID)
)
GO

CREATE TABLE ORDER_TABLE
(
	ID INT IDENTITY(1, 1) NOT NULL,
	ID_CUSTOMER INT,
	ID_STAFF INT,
	DELIVERY_ADDRESS NVARCHAR(255),
	DELIVERY_DATE DATE,
	RECIPIENT_PHONE VARCHAR(50),
	RECIPIENT_NAME NVARCHAR(50),
	DATE_CREATED DATE,
	ORDER_STATUS INT,
	PAYMENT_TYPE INT,
	DELIVERY_COST DECIMAL(19,4),
	TOTAL_MONEY DECIMAL(19,4),

	CONSTRAINT PK_ORDER
	PRIMARY KEY (ID)
)
GO

CREATE TABLE ORDER_DETAIL
(
	ID_ORDER INT,
	ID_PRODUCT INT,
	QUANTITY INT,
	AMOUNT DECIMAL(19,4),

	CONSTRAINT PK_ORDER_DETAIL
	PRIMARY KEY (ID_ORDER, ID_PRODUCT)
)
GO

CREATE TABLE BRANCH
(
	ID INT IDENTITY(1, 1) NOT NULL,
	NAME NVARCHAR(50),
	ADDRESS NVARCHAR(255),

	CONSTRAINT PK_BRANCH
	PRIMARY KEY (ID)
)
GO

CREATE TABLE PRODUCT
(
	ID INT IDENTITY(1, 1) NOT NULL,
	NAME NVARCHAR(50),
	DESCRIPTION NVARCHAR(255),
	IMAGE VARCHAR(255),
	QUANTITY INT,
	PRICE DECIMAL(19,4),

	CONSTRAINT PK_PRODUCT
	PRIMARY KEY (ID)
)
GO

CREATE TABLE PRODUCT_BRANCH
(
	ID_PRODUCT INT,
	ID_BRANCH INT,

	CONSTRAINT PK_PRODUCT_BRANCH
	PRIMARY KEY (ID_PRODUCT,ID_BRANCH)
)
GO

ALTER TABLE STAFF
ADD
	CONSTRAINT FK_STAFF_USER
	FOREIGN KEY(ID_USER)
	REFERENCES USER_TABLE(ID)
GO

ALTER TABLE CUSTOMER
ADD
	CONSTRAINT FK_CUSTOMER_USER
	FOREIGN KEY(ID_USER)
	REFERENCES USER_TABLE(ID)
GO