USE MASTER
GO

IF DB_ID('QLBH') IS NOT NULL 
	DROP DATABASE QLBH
GO

CREATE DATABASE QLBH
GO

USE QLBH
GO

CREATE TABLE M_USER
(
	ID INT IDENTITY(1, 1) NOT NULL,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	FULLNAME NVARCHAR(255),
	DOB DATETIME,
	ROLE INT,

	CONSTRAINT PK_USER
	PRIMARY KEY (ID)
)
GO

CREATE TABLE M_CUSTOMER
(
	ID INT IDENTITY(1, 1) NOT NULL,
	FULLNAME NVARCHAR(255),
	SDT VARCHAR(20),

	CONSTRAINT PK_CUSTOMER
	PRIMARY KEY (ID)
)
GO

CREATE TABLE M_ORDER
(
	ID INT IDENTITY(1, 1) NOT NULL,
	ID_CUSTOMER INT,
	ID_STAFF INT,
	DELIVERY_ADDRESS NVARCHAR(255),
	DELIVERY_DATE DATE,
	RECIPIENT_NAME NVARCHAR(50),
	RECIPIENT_PHONE VARCHAR(50),
	DATE_CREATED DATE,
	ORDER_STATUS INT,
	PAYMENT_TYPE INT,
	DELIVERY_COST DECIMAL(19,4),
	TOTAL_MONEY DECIMAL(19,4),

	CONSTRAINT PK_ORDER
	PRIMARY KEY (ID)
)
GO

CREATE TABLE M_ORDER_DETAIL
(
	ID_ORDER INT,
	ID_PRODUCT INT,
	QUANTITY INT,
	AMOUNT DECIMAL(19,4),

	CONSTRAINT PK_M_ORDER_DETAIL
	PRIMARY KEY (ID_ORDER, ID_PRODUCT)
)
GO


CREATE TABLE M_PRODUCT
(
	ID INT IDENTITY(1, 1) NOT NULL,
	NAME NVARCHAR(50),
	DESCRIPTION NVARCHAR(255),
	IMAGE VARCHAR(255),
	QUANTITY INT,
	PRICE DECIMAL(19,4),

	CONSTRAINT PK_PRODUCT
	PRIMARY KEY (ID)
)
GO


------------------------------
ALTER TABLE M_ORDER
ADD
	CONSTRAINT FK_ORDER_USER
	FOREIGN KEY(ID_STAFF)
	REFERENCES M_USER(ID),

	CONSTRAINT FK_ORDER_CUSTOMER
	FOREIGN KEY(ID_CUSTOMER)
	REFERENCES M_CUSTOMER(ID)
GO

ALTER TABLE M_ORDER_DETAIL
ADD
	CONSTRAINT FK_ORDERDETAIL_PRODUCT
	FOREIGN KEY(ID_PRODUCT)
	REFERENCES M_PRODUCT(ID),

	CONSTRAINT FK_ORDERDETAIL_ORDER
	FOREIGN KEY(ID_ORDER)
	REFERENCES M_ORDER(ID)
GO